### ISSUE TITLE
[Bug] Juni fails without any errors, resulting in no sticker

### ISSUE THREAD

**Issue by techygrrrl** [folklorelabs/pockest-helper#117] opened 2024-09-13 18:00 UTC
Juni's last match didn't happen and there was no error. I am assuming this is why it resulted in a failure.

The missing match care log result was blank after the period it was supposed to happen and before age 5, then turned into a warning sign.

version 1.2.0

<details>
<summary>Care log</summary>

```
[9/10/2024, 12:52:27 PM] Jelly hatched (🥚#8)
[9/10/2024, 12:52:30 PM] Jelly fed (❤️0 → 1)
[9/10/2024, 12:52:32 PM] Jelly fed (❤️1 → 2)
[9/10/2024, 12:52:33 PM] Jelly fed (❤️2 → 3)
[9/10/2024, 12:52:35 PM] Jelly fed (❤️3 → 4)
[9/10/2024, 12:52:36 PM] Jelly fed (❤️4 → 5)
[9/10/2024, 12:52:37 PM] Jelly fed (❤️5 → 6)
[9/10/2024, 12:52:39 PM] Jelly trained speed (+110🏃🏻)
[9/10/2024, 1:52:47 PM] Ami appears (P: 0, S: 110, T: 0)
[9/10/2024, 1:52:47 PM] Ami appears (P: 0, S: 110, T: 0)
[9/11/2024, 12:52:47 AM] Rime appears (P: 0, S: 110, T: 0)
[9/11/2024, 12:52:49 AM] Rime trained power (+144🏋️)
[9/11/2024, 12:52:50 PM] Rime cleaned (💩12 → 0)
[9/11/2024, 12:52:51 PM] Rime fed (❤️0 → 1)
[9/11/2024, 12:52:54 PM] Rime fed (❤️1 → 2)
[9/11/2024, 12:52:56 PM] Rime fed (❤️2 → 3)
[9/11/2024, 12:52:57 PM] Rime trained power (+156🏋️)
[9/12/2024, 12:52:48 AM] Adamante appears (P: 300, S: 110, T: 0)
[9/12/2024, 12:52:49 AM] Adamante cleaned (💩5 → 0)
[9/12/2024, 12:52:51 AM] Adamante fed (❤️0 → 1)
[9/12/2024, 12:52:53 AM] Adamante fed (❤️1 → 2)
[9/12/2024, 12:52:55 AM] Adamante fed (❤️2 → 3)
[9/12/2024, 12:52:57 AM] Adamante fed (❤️3 → 4)
[9/12/2024, 12:52:59 AM] Adamante fed (❤️4 → 5)
[9/12/2024, 12:53:02 AM] Adamante fed (❤️5 → 6)
[9/12/2024, 12:53:03 AM] Adamante trained technic (+196🤸🏻)
[9/12/2024, 12:53:06 AM] Adamante vs Pippin (+227 egg)
[9/12/2024, 4:52:30 AM] Adamante fed (❤️5 → 6)
[9/12/2024, 6:52:52 AM] Adamante cleaned (💩3 → 0)
[9/12/2024, 8:52:30 AM] Adamante fed (❤️5 → 6)
[9/12/2024, 12:53:48 PM] Adamante trained technic (+210🤸🏻)
```

</details>

<details>
<summary>Plan</summary>

```
[Pockest Helper v1.2.0] Target 8CRT5 (Age 5)
☑ [9/10/2024, 12:52:27 PM] Feed (♥♥♥♥♥♥)
☑ [9/10/2024, 12:52:27 PM] Train S
☑ [9/11/2024, 12:52:27 AM] Train P
☑ [9/11/2024, 12:52:27 PM] Clean
☑ [9/11/2024, 12:52:27 PM] Feed (♥♥♥♡♡♡)
☑ [9/11/2024, 12:52:27 PM] Train P
☑ [9/12/2024, 12:52:27 AM] Clean
☑ [9/12/2024, 12:52:27 AM] Feed (♥♥♥♥♥♥)
☑ [9/12/2024, 12:52:27 AM] Train T
☑ [9/12/2024, 12:52:27 AM] Match
☑ [9/12/2024, 4:52:27 AM] Feed (♥♥♥♥♥♥)
☑ [9/12/2024, 6:52:27 AM] Clean
☑ [9/12/2024, 8:52:27 AM] Feed (♥♥♥♥♥♥)
☑ [9/12/2024, 12:52:27 PM] Train T
⚠ [9/13/2024, 12:52:27 AM] Match
☑ [9/13/2024, 8:52:27 AM] Stop curing
```

</details>

<img width="959" alt="pockest - juni - skip match" src="https://github.com/user-attachments/assets/7c3a7fa3-2b5a-44aa-a7f1-9c655a4887a4">

<img width="971" alt="pockest helper - juni - no match" src="https://github.com/user-attachments/assets/ad56c1a8-dda9-4b5a-a394-2426e6a1f4f6">

**Comment by techygrrrl** [comment] 2024-09-13 18:11
In the plan, can we include details about the match that's supposed to happen? In case it fails, we can manually recover it? I wasn't sure if I should intervene and if I did, what I should've gone for.

**Comment by folklorelabs** [comment] 2024-09-17 00:20
Nothing went wrong here. This is just an error with the preset plan log showing one too many matches. Your monster should have been stunned at this point and thus wouldn't be able to match anyway. I'll make sure to update the preset plan logic to account for this with the "sticker only" plan in this next version

Thanks for the heads up :D

**Comment by folklorelabs** [comment] 2024-09-17 00:39
Looks like it was actually fixed in my current rc version actually. I'm just going to cut this version now because it's been stable for a few weeks now.

**Comment by folklorelabs** [comment] 2024-09-17 00:43
Should be fixed in [v1.2.2](https://github.com/folklorelabs/pockest-helper/releases/tag/v1.2.2).

**Comment by techygrrrl** [comment] 2024-09-17 01:49
Sorry, just trying to understand. You said:

> Your monster should have been stunned at this point and thus wouldn't be able to match anyway. I'll make sure to update the preset plan logic to account for this when the user selects the "sticker only" plan

Then you said:

> Looks like it was actually fixed in my current rc version actually. 

To clarify, are you saying there was actually a problem and it's fixed? I didn't get the sticker so something was broken. So if it didn't fail because of the missed match, it must've failed for another unreported reason, because there were no errors.

**Comment by folklorelabs** [comment] 2024-09-27 22:35
Sorry I missed this comment! This was a problem in `v1.2.0`, but was actually fixed in `v1.2.1`. So you should be good to pull the latest version [v1.2.2](https://github.com/folklorelabs/pockest-helper/releases/tag/v1.2.2) and it will be fixed in there.

**Comment by folklorelabs** [comment] 2024-09-27 22:43
Did you do any matches outside of the helper by chance? If you did that can cause a failure.

**Comment by folklorelabs** [comment] 2024-09-27 22:55
Hrmm, looking at your log I'm seeing you trained SPPTT which is very wrong? Juni is PPTTTT and defaults to training T so I have no idea how it would have trained S? Confirmed this is the case in both the spreadsheet and [the live data](https://folklorelabs.io/pockest-helper-data/v2/monsters.json). The only thing I can think of is that SHIII3rd had a different path in there 2 weeks ago? I don't think I've trained her yet so I will add her to my queue next to verify that it's working properly on `v1.2.2`.
![image](https://github.com/user-attachments/assets/c93d4a12-4c96-4166-8edc-f1ce7d83959b)

**Comment by folklorelabs** [comment] 2024-09-30 17:20
Confirmed it's following the Juni path correctly on my end :(
```
[9/28/2024, 06:35:10 PM] Jelly hatched (🥚#8)
[9/28/2024, 06:35:12 PM] Jelly fed (❤️0 → 1)
[9/28/2024, 06:35:14 PM] Jelly fed (❤️1 → 2)
[9/28/2024, 06:35:15 PM] Jelly fed (❤️2 → 3)
[9/28/2024, 06:35:17 PM] Jelly fed (❤️3 → 4)
[9/28/2024, 06:35:18 PM] Jelly fed (❤️4 → 5)
[9/28/2024, 06:35:20 PM] Jelly fed (❤️5 → 6)
[9/28/2024, 06:35:21 PM] Jelly trained power (+110🏋️)
[9/28/2024, 07:35:11 PM] Ami appears (P: 110, S: 0, T: 0)
[9/29/2024, 06:35:11 AM] Rime appears (P: 110, S: 0, T: 0)
[9/29/2024, 06:35:21 AM] Rime trained power (+144🏋️)
[9/29/2024, 06:35:12 PM] Rime cleaned (💩12 → 0)
[9/29/2024, 06:35:14 PM] Rime fed (❤️0 → 1)
[9/29/2024, 06:35:16 PM] Rime fed (❤️1 → 2)
[9/29/2024, 06:35:18 PM] Rime fed (❤️2 → 3)
[9/29/2024, 06:35:24 PM] Rime trained technic (+117🤸🏻)
[9/30/2024, 06:35:12 AM] Adamante appears (P: 254, S: 0, T: 117)
[9/30/2024, 06:35:14 AM] Adamante cleaned (💩6 → 0)
[9/30/2024, 06:35:16 AM] Adamante fed (❤️0 → 1)
[9/30/2024, 06:35:17 AM] Adamante fed (❤️1 → 2)
[9/30/2024, 06:35:18 AM] Adamante fed (❤️2 → 3)
[9/30/2024, 06:35:20 AM] Adamante fed (❤️3 → 4)
[9/30/2024, 06:35:21 AM] Adamante fed (❤️4 → 5)
[9/30/2024, 06:35:23 AM] Adamante fed (❤️5 → 6)
[9/30/2024, 06:35:25 AM] Adamante trained technic (+196🤸🏻)
[9/30/2024, 06:35:27 AM] Adamante vs Virtuoso (+249 egg)
```

Not sure what happened for you. The log shows it training stats that it should not have, but I have never gotten it to behave that way. Let me know if you can figure out a way to reproduce this.

**Closed by folklorelabs** 2024-09-30 17:20 UTC

**Comment by techygrrrl** [comment] 2024-10-03 17:20
Thanks for clarifying. I'll pull the latest update and try out Juni again.

**Comment by techygrrrl** [comment] 2024-10-03 17:40
I did not perform any manual actions. One thing I did notice when looking at your logs vs. mine, is that mine trained speed when yours trained power at the initial training (Jelly trained, before Ami appears). Your stats are power 110 and mine are speed 110. Then the next training, mine trained power when yours trained technique (Rime's training before Adamante appears).

The next difference, Adamante had 5 poops when it was cleaned while yours had 6 poops.

It looks like then mine had a match Adamante vs. Pippin while yours had a match Adamante vs. Virtuoso.

The last common action between ours was training technique, then the match discrepancy described above happened, after which point, mine continued performing subsequent actions, maybe you didn't paste the full log?:

```
[9/12/2024, 4:52:30 AM] Adamante fed (❤️5 → 6)
[9/12/2024, 6:52:52 AM] Adamante cleaned (💩3 → 0)
[9/12/2024, 8:52:30 AM] Adamante fed (❤️5 → 6)
[9/12/2024, 12:53:48 PM] Adamante trained technic (+210🤸🏻)
```

Anyhow, I'm not sure how to debug this but in summary it looks like:

- initial training has a discrepancy in the stat that is trained (my speed vs. your power)
- number of poops before a cleaning is a discrepancy (my 5 vs your 6)
- match vs. a different monster (not sure how the matches work but maybe this could be part of the issue)

If only logging changes were made, then I'm not sure they'd work to fix the issue 🤔  Either way, I'm giving Juni a try with version 1.2.3 and will report back, but the discrepancy in stat trained, poops it had before cleaning, and training partner all seem to be different, not sure if they matter.

**Comment by techygrrrl** [comment] 2024-10-03 17:46
To follow up, I see the diagram you shared also seems to show Juni weighted in power and technique. Mine has a speed training in there 🤔 

```
[9/10/2024, 12:52:39 PM] Jelly trained speed (+110🏃🏻)
```

![image](https://github.com/user-attachments/assets/caf02c52-fbbe-486d-bb95-632731992358)


Not sure if that's where the issue is? It seemed to follow the path of the tree otherwise, not sure how late/early discrepancies can happen.

**Comment by techygrrrl** [comment] 2024-10-05 03:09
One thing I noticed about the plan is in the initial version I used for Juni (1.2.0) the plan was SPPTTT whereas in the new version 1.2.3 it's PPTTTT.

Old:

![image](https://github.com/user-attachments/assets/c337c836-231a-4bb4-99d0-f8a4d32debf8)

New:

![image](https://github.com/user-attachments/assets/e957b79e-6808-408f-8491-494ceb11a847)

So the plan looks like it's more inline with what your successful path experienced. I'll let you know how it works out.

**Comment by techygrrrl** [comment] 2024-10-07 03:59
This run was successful. 🎉  Not sure what happened between the versions but will assume the stat plan was wrong for my initial plan for Juni. Is the stat plan data from a server? I didn't get a chance to look into it but if it is, maybe the data was wrong for this period of time and has since been resolved.
